services:
  web:
    build: web
    stop_signal: SIGINT
    ports:
      - "8000:8000"
      - "8082:8082"
    env_file:
      - .env
    networks:
      - frontnet

  proxy:
    build: proxy
    restart: always
    ports:
      - 80:80
    depends_on:
      - web
    networks:
      - frontnet

networks:
  frontnet:
