name: reader

services:
  app:
    image: registry.digitalocean.com/minond/reader-app
    build: app
    stop_signal: SIGINT
    ports:
      - 8000:8000
      - 8082:8082
    env_file:
      - .env
    networks:
      - frontnet

  proxy:
    image: registry.digitalocean.com/minond/reader-proxy
    build: proxy
    restart: always
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - frontnet

networks:
  frontnet:
